### ISSUE TITLE
geo.captcha-delivery检测过不了

### ISSUE THREAD

**Issue by maitel2020** [Virtual-Browser/VirtualBrowser#1]
VirtualBrowser访问  https://www.cedeo.fr  时被检查出来，清缓存、换ip都无法通过，使用ads或比特浏览器是可以访问的
![image](https://github.com/Virtual-Browser/VirtualBrowser/assets/38597715/c1f75160-e152-451d-8c6c-616d6f9e7688)

**Comment by virtualfanc** [comment]
请使用最新版本验证
