### ISSUE TITLE
请问 chromium 修改部分也开源吗

### ISSUE THREAD

**Issue by eric-gitta-moore** [Virtual-Browser/VirtualBrowser#18]
请问 chromium 修改部分也开源吗

在 main 分支和几个 tag 分支似乎只看到了标签页的代码

**Comment by FPEsocrter** [comment]
> 请问 chromium 修改部分也开源吗
> 
> 在 main 分支和几个 tag 分支似乎只看到了标签页的代码

可以看这个 https://github.com/FPEsocrter/openFpchromium   项目 内核完整开源 ， 和商业版的没差异， 过99% 检测网站0

**Comment by eric-gitta-moore** [comment]
> > 请问 chromium 修改部分也开源吗
> > 在 main 分支和几个 tag 分支似乎只看到了标签页的代码
> 
> 可以看这个 https://github.com/FPEsocrter/openFpchromium 项目 内核完整开源 ， 和商业版的没差异， 过99% 检测网站0

感谢

**Comment by Virtual-Browser** [comment]
暂不开源
