### ISSUE TITLE
IP查询API设置第三方ipgeolocation接口无效

### ISSUE THREAD

**Issue by yinXtang** [Virtual-Browser/VirtualBrowser#29]
IP查询API设置第三方ipgeolocation接口无效，其格式设置如下

https://api.ipgeolocation.io/ipgeo-bulk?apiKey=6e969*********************1ed4b13

是我链接设置错了吗？
官方接口有效，但因为查询次数有限，所以还是更倾向于用第三方的

**Comment by yunxilyf** [comment]
> IP查询API设置第三方ipgeolocation接口无效，其格式设置如下
> 
> https://api.ipgeolocation.io/ipgeo-bulk?apiKey=6e969*********************1ed4b13
> 
> 是我链接设置错了吗？ 官方接口有效，但因为查询次数有限，所以还是更倾向于用第三方的

你链接错了吧

**Comment by yinXtang** [comment]
> > IP查询API设置第三方ipgeolocation接口无效，其格式设置如下
> > https://api.ipgeolocation.io/ipgeo-bulk?apiKey=6e969*********************1ed4b13
> > 是我链接设置错了吗？ 官方接口有效，但因为查询次数有限，所以还是更倾向于用第三方的
> 
> 你链接错了吧

错在哪里？链接格式是怎样的，说清楚点啊
在它的官网，我就找到这么一个靠谱一点的API链接格式，直接复制只能复制到apikey
